- id: doi:10.1038/s43587-025-00897-z
  type: paper
  title: DunedinPACNI estimates the longitudinal Pace of Aging from a single brain image to track health and disease
  description: Tool to measure the rate of aging from a single brain scan.
  authors:
  - Ethan T. Whitman
  - Maxwell L. Elliott
  - Annchen R. Knodt
  - Wickliffe C. Abraham
  - Tim J. Anderson
  - Nicholas J. Cutfield
  - Sean Hogan
  - David Ireland
  - Tracy R. Melzer
  - Sandhya Ramrakha
  - Karen Sugden
  - Reremoana Theodore
  - Benjamin S. Williams
  - Avshalom Caspi
  - Terrie E. Moffitt
  - Ahmad R. Hariri
  publisher: Nature Aging
  date: '2025-07-01'
  link: https://doi.org/g9rwr5
  orcid: 0000-0003-1083-6277
  maxwell-elliott: true
  image: https://media.springernature.com/full/springer-static/image/art%3A10.1038%2Fs43587-025-00897-z/MediaObjects/43587_2025_897_Fig1_HTML.png?as=webp
  buttons:
    - type: source
      text: Github
      link: https://github.com/etw11/DunedinPACNI

